CREATE TABLE `broadcast_session` (
  `id` VARCHAR(191) NOT NULL,
  `title` VARCHAR(120) NOT NULL,
  `tournamentId` VARCHAR(191) NOT NULL,
  `venueId` VARCHAR(191) NULL,
  `currentMatchId` VARCHAR(191) NULL,
  `createdById` VARCHAR(191) NULL,
  `enabled` BOOLEAN NOT NULL DEFAULT true,
  `isPublic` BOOLEAN NOT NULL DEFAULT false,
  `status` ENUM('READY', 'LIVE', 'INTERRUPTED', 'ENDED') NOT NULL DEFAULT 'READY',
  `overlayTokenHash` VARCHAR(64) NOT NULL,
  `overlaySettings` JSON NULL,
  `configVersion` INTEGER NOT NULL DEFAULT 1,
  `playbackUrl` VARCHAR(1000) NULL,
  `provider` VARCHAR(40) NULL,
  `streamName` VARCHAR(120) NULL,
  `startedAt` DATETIME(3) NULL,
  `endedAt` DATETIME(3) NULL,
  `lastStreamEventAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `broadcast_session_overlayTokenHash_key` (`overlayTokenHash`),
  INDEX `broadcast_session_tournamentId_idx` (`tournamentId`),
  INDEX `broadcast_session_currentMatchId_idx` (`currentMatchId`),
  INDEX `broadcast_session_venueId_idx` (`venueId`),
  CONSTRAINT `broadcast_session_tournament_fkey` FOREIGN KEY (`tournamentId`) REFERENCES `Tournament` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `broadcast_session_venue_fkey` FOREIGN KEY (`venueId`) REFERENCES `Venue` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `broadcast_session_match_fkey` FOREIGN KEY (`currentMatchId`) REFERENCES `Match` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
