// Camera app API acceptance: pairing, config, heartbeat, and the guarantee that
// the push URL never leaves the camera-token boundary.
//   node --env-file=.env test/camera.smoke.cjs
const assert = require('node:assert/strict');
const path = require('node:path');
const { randomUUID } = require('node:crypto');
const { PrismaClient } = require('@prisma/client');
const { PrismaMariaDb } = require('@prisma/adapter-mariadb');
const { JwtService } = require('@nestjs/jwt');

const prisma = new PrismaClient({ adapter: new PrismaMariaDb(process.env.DATABASE_URL) });
const api = process.env.QA_API_URL || 'http://localhost:4000/api';
const ids = { root: randomUUID(), admin: randomUUID(), tournament: randomUUID() };


async function call(endpoint, { token, cameraToken, method = 'GET', body, expected = 200 } = {}) {
  const headers = { 'Content-Type': 'application/json' };
  if (token) headers.Authorization = `Bearer ${token}`;
  if (cameraToken) headers.Authorization = `Bearer ${cameraToken}`;
  const response = await fetch(`${api}${endpoint}`, {
    method, headers, ...(body ? { body: JSON.stringify(body) } : {}),
  });
  const text = await response.text();
  assert.equal(response.status, expected, `${method} ${endpoint} -> ${response.status}: ${text}`);
  return text ? JSON.parse(text) : null;
}

async function main() {
  const jwt = new JwtService({ secret: process.env.JWT_SECRET });
  for (const [id, role] of [[ids.root, 'ROOT'], [ids.admin, 'ADMIN']]) {
    await prisma.user.create({ data: {
      id, username: `cam-${role}-${id}`, email: `${id}@camera.invalid`, passwordHash: 'unused', role,
    } });
  }
  const rootToken = jwt.sign({ sub: ids.root }, { expiresIn: '20m' });
  const adminToken = jwt.sign({ sub: ids.admin }, { expiresIn: '20m' });
  await prisma.tournament.create({ data: {
    id: ids.tournament, name: '摄像端接口验收赛', startDate: new Date(),
    endDate: new Date(Date.now() + 86400000), status: 'ONGOING', approvalStatus: 'APPROVED',
    isPublished: true, submittedById: ids.root,
  } });

  // --- Management is still ROOT-only ---------------------------------------
  await call('/broadcasts', { method: 'POST', expected: 401, body: { title: 'x', tournamentId: ids.tournament } });
  await call('/broadcasts', { method: 'POST', token: adminToken, expected: 403, body: { title: 'x', tournamentId: ids.tournament } });

  const created = await call('/broadcasts', {
    method: 'POST', token: rootToken, expected: 201,
    body: { title: '摄像端直播间', tournamentId: ids.tournament },
  });
  assert.equal(created.camera.paired, false, '新建时未配对摄像端');
  assert.equal(created.camera.hasIngestUrl, false);
  assert.equal(created.camera.online, false);

  // Push and playback URLs are generated by the media service, never manually entered.
  let detail = await call(`/broadcasts/${created.id}`, { token: rootToken });
  await call(`/broadcasts/${created.id}`, {
    method: 'PATCH', token: rootToken, expected: 400,
    body: { configVersion: detail.configVersion, ingestUrl: 'rtmp://push.example.com/live/forbidden' },
  });
  await call(`/broadcasts/${created.id}`, {
    method: 'PATCH', token: rootToken, expected: 400,
    body: { configVersion: detail.configVersion, playbackUrl: 'https://live.example.com/live/forbidden.m3u8' },
  });
  assert.equal(detail.camera.hasIngestUrl, false);

  // --- Camera endpoints need no account, but need the token -----------------
  await call('/camera/config', { expected: 401 });
  await call('/camera/config', { cameraToken: 'not-a-real-token', expected: 401 });

  const paired = await call(`/broadcasts/${created.id}/pair-camera`, { method: 'POST', token: rootToken, expected: 201 });
  const cameraToken = paired.cameraToken;
  assert.ok(cameraToken && cameraToken.length > 20, '配对令牌一次性返回');
  // The QR code needs an address the phone can reach; localhost never qualifies.
  assert.ok(Array.isArray(paired.serverUrls), '配对时给出手机可用的后台地址列表');
  for (const url of paired.serverUrls) {
    assert.match(url, /^https?:\/\//, `地址需为 http(s)：${url}`);
    assert.ok(!/\/\/(localhost|127\.)/.test(url), `不能给手机 localhost：${url}`);
    assert.ok(!url.endsWith('/api'), `地址不带 /api：${url}`);
  }
  detail = await call(`/broadcasts/${created.id}`, { token: rootToken });
  assert.equal(detail.camera.paired, true);
  assert.ok(!JSON.stringify(detail).includes(cameraToken), '后台不再回显配对令牌');

  const config = await call('/camera/config', { cameraToken });
  assert.equal(config.broadcastId, created.id);
  assert.ok(/^rtmp:\/\/[^/]+:\d+\/[A-Za-z0-9_-]{24}\?token=[A-Za-z0-9_-]{32}$/.test(config.ingestUrl), '系统自动生成带房间密钥的推流地址');
  assert.equal(config.tournamentName, '摄像端接口验收赛');
  // Resolution and frame rate are the phone's business: it picks them from what
  // its own camera and encoder can do in 16:9, and reports them by heartbeat.
  assert.equal(config.settings.resolution, undefined, '不再下发分辨率');
  assert.equal(config.settings.fps, undefined, '不再下发帧率');
  assert.equal(config.settings.preferExternalMic, true);
  // Zero means "no limit": the phone sizes the bitrate for the tier it measured.
  assert.equal(config.settings.videoBitrateKbps, 0, '默认不限制码率');
  assert.deepEqual(Object.keys(config).sort(), [
    'broadcastId', 'configVersion', 'ingestUrl', 'settings', 'status', 'title', 'tournamentName', 'venueName',
  ].sort(), '不给 App 多余字段');

  // --- Heartbeat drives the admin online light ------------------------------
  const beat = await call('/camera/heartbeat', {
    method: 'POST', cameraToken, expected: 201,
    body: { state: 'STREAMING', bitrateKbps: 6200, fps: 30, width: 1920, height: 1080, zoom: 2.5, audioSource: 'DJI Mic 2', battery: 76 },
  });
  assert.equal(beat.broadcastId, created.id, '心跳同时回配置');
  detail = await call(`/broadcasts/${created.id}`, { token: rootToken });
  assert.equal(detail.camera.online, true, '刚上报即在线');
  assert.equal(detail.camera.state.state, 'STREAMING');
  assert.equal(detail.camera.state.zoom, 2.5);
  assert.equal(detail.camera.state.audioSource, 'DJI Mic 2');

  // A heartbeat outside the enum is refused.
  await call('/camera/heartbeat', { method: 'POST', cameraToken, expected: 400, body: { state: 'FLYING' } });

  // The transient states the app reports while (re)connecting must be accepted,
  // otherwise the admin page would only ever see a degraded "idle".
  for (const transitional of ['CONNECTING', 'RECONNECTING']) {
    const beat2 = await call('/camera/heartbeat', {
      method: 'POST', cameraToken, expected: 201,
      body: { state: transitional, message: `${transitional} 测试` },
    });
    assert.equal(beat2.broadcastId, created.id, `${transitional} 心跳应被接受`);
    detail = await call(`/broadcasts/${created.id}`, { token: rootToken });
    assert.equal(detail.camera.state.state, transitional);
    assert.equal(detail.camera.state.message, `${transitional} 测试`);
  }

  // --- Disabling the room cuts the app off ---------------------------------
  detail = await call(`/broadcasts/${created.id}`, {
    method: 'PATCH', token: rootToken,
    body: { configVersion: detail.configVersion, enabled: false },
  });
  await call('/camera/config', { cameraToken, expected: 401 });
  await call('/camera/heartbeat', { method: 'POST', cameraToken, expected: 401, body: { state: 'IDLE' } });
  detail = await call(`/broadcasts/${created.id}`, {
    method: 'PATCH', token: rootToken,
    body: { configVersion: detail.configVersion, enabled: true },
  });
  assert.equal((await call('/camera/config', { cameraToken })).broadcastId, created.id, '重新启用后恢复');

  // --- Camera settings reach the app ---------------------------------------
  detail = await call(`/broadcasts/${created.id}`, {
    method: 'PATCH', token: rootToken,
    body: {
      configVersion: detail.configVersion,
      cameraSettings: { videoBitrateKbps: 8000, audioBitrateKbps: 96, facing: 'front', preferExternalMic: false },
    },
  });
  const tuned = await call('/camera/config', { cameraToken });
  assert.equal(tuned.settings.videoBitrateKbps, 8000);
  assert.equal(tuned.settings.facing, 'front');
  assert.equal(tuned.settings.preferExternalMic, false);

  // The cap must accept 0 (no limit) and reject values outside the DTO bounds,
  // so a stray negative cannot reach the encoder.
  detail = await call(`/broadcasts/${created.id}`, {
    method: 'PATCH', token: rootToken,
    body: {
      configVersion: detail.configVersion,
      cameraSettings: { videoBitrateKbps: 0, audioBitrateKbps: 96, facing: 'front', preferExternalMic: false },
    },
  });
  assert.equal((await call('/camera/config', { cameraToken })).settings.videoBitrateKbps, 0, '0 表示不限码率');
  await call(`/broadcasts/${created.id}`, {
    method: 'PATCH', token: rootToken, expected: 400,
    body: {
      configVersion: detail.configVersion,
      cameraSettings: { videoBitrateKbps: -1, audioBitrateKbps: 96, facing: 'front', preferExternalMic: false },
    },
  });
  detail = await call(`/broadcasts/${created.id}`, {
    method: 'PATCH', token: rootToken,
    body: {
      configVersion: detail.configVersion,
      cameraSettings: { videoBitrateKbps: 8000, audioBitrateKbps: 96, facing: 'front', preferExternalMic: false },
    },
  });

  // A row still holding pre-upgrade resolution/fps must not leak them back to
  // the app, or the phone would keep honouring a quality nobody can change now.
  // Its bitrate goes too: it was a hint the app overrode, and it is a hard cap
  // now, so reusing it would pin a 4K phone to the old 6000 default.
  await prisma.broadcastSession.update({
    where: { id: created.id },
    data: { cameraSettings: { videoBitrateKbps: 8000, audioBitrateKbps: 96, facing: 'front', preferExternalMic: false, resolution: '2160p', fps: 60 } },
  });
  const legacy = await call('/camera/config', { cameraToken });
  assert.equal(legacy.settings.resolution, undefined, '历史分辨率字段被过滤');
  assert.equal(legacy.settings.fps, undefined, '历史帧率字段被过滤');
  assert.equal(legacy.settings.videoBitrateKbps, 0, '历史码率按不限处理，不再当成上限');
  // The operator's other fields survive the filter.
  assert.equal(legacy.settings.audioBitrateKbps, 96);
  assert.equal(legacy.settings.facing, 'front');

  // --- The app can unpair itself; admin can force it ------------------------
  await call('/camera/unpair', { method: 'POST', cameraToken, expected: 201 });
  await call('/camera/config', { cameraToken, expected: 401 });
  detail = await call(`/broadcasts/${created.id}`, { token: rootToken });
  assert.equal(detail.camera.paired, false);
  assert.equal(detail.camera.online, false);

  const again = await call(`/broadcasts/${created.id}/pair-camera`, { method: 'POST', token: rootToken, expected: 201 });
  assert.notEqual(again.cameraToken, cameraToken, '重新配对得到新令牌');
  await call(`/broadcasts/${created.id}/unpair-camera`, { method: 'POST', token: rootToken, expected: 201 });
  await call('/camera/config', { cameraToken: again.cameraToken, expected: 401, });

  // --- Deleting the room invalidates everything ----------------------------
  const doomed = await call('/broadcasts', {
    method: 'POST', token: rootToken, expected: 201,
    body: { title: '待删除直播间', tournamentId: ids.tournament },
  });
  const doomedPair = await call(`/broadcasts/${doomed.id}/pair-camera`, { method: 'POST', token: rootToken, expected: 201 });
  await call(`/broadcasts/${doomed.id}`, { method: 'DELETE', token: rootToken });
  await call('/camera/config', { cameraToken: doomedPair.cameraToken, expected: 401 });

  console.log('camera smoke: OK');
}

main()
  .catch((error) => { console.error(error); process.exitCode = 1; })
  .finally(async () => {
    await prisma.broadcastSession.deleteMany({ where: { tournamentId: ids.tournament } });
    await prisma.tournament.deleteMany({ where: { id: ids.tournament } });
    await prisma.user.deleteMany({ where: { id: { in: [ids.root, ids.admin] } } });
    await prisma.$disconnect();
  });
