const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { createRequire } = require('node:module');
const frontend = path.resolve(__dirname, '../../frontend');
const localRequire = createRequire(path.join(frontend, 'package.json'));
const ts = localRequire('typescript');
const { VideoQuality } = localRequire('livekit-client');
const source = fs.readFileSync(path.join(frontend, 'lib/live-video-quality.ts'), 'utf8');
const compiled = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 } }).outputText;
const fixture = { exports: {} };
new Function('require', 'exports', 'module', compiled)(localRequire, fixture.exports, fixture);
const { retainVideoQuality } = fixture.exports;
let selected;
const publication = { setVideoQuality: (value) => { selected = value; } };
const card = retainVideoQuality(publication, 'low');
assert.equal(selected, VideoQuality.LOW);
const pgm = retainVideoQuality(publication, 'high');
assert.equal(selected, VideoQuality.HIGH);
const remountedCard = retainVideoQuality(publication, 'low');
assert.equal(selected, VideoQuality.HIGH, 'thumbnail mounting after PGM must not downgrade the shared track');
card();
assert.equal(selected, VideoQuality.HIGH);
const pvw = retainVideoQuality(publication, 'high');
pgm();
assert.equal(selected, VideoQuality.HIGH, 'remaining PVW still needs the high layer');
pvw();
assert.equal(selected, VideoQuality.LOW, 'unselected camera can return to thumbnail quality');
remountedCard();
const newPgm = retainVideoQuality(publication, 'high');
remountedCard();
assert.equal(selected, VideoQuality.HIGH, 'repeated stale cleanup must not affect a new subscription');
newPgm();
console.log('PASS: thumbnail/PGM/PVW quality arbitration, unmount downgrade and stale cleanup');
