// Real local DB concurrency test; does not require a media server or browser.
const assert = require('node:assert/strict');
const { randomUUID } = require('node:crypto');
const { PrismaClient } = require('@prisma/client');
const { PrismaMariaDb } = require('@prisma/adapter-mariadb');
const { MulticameraService } = require('../dist/broadcasts/multicamera.service');
const url = new URL(process.env.DATABASE_URL);
if (!['localhost', '127.0.0.1'].includes(url.hostname)) throw new Error('Local test database required');
const db = new PrismaClient({ adapter: new PrismaMariaDb(process.env.DATABASE_URL) });
const live = new MulticameraService(db, { configured: () => true, call: async () => ({}), participants: async () => [] }, {});
const id = randomUUID();
const actor = { id: randomUUID(), role: 'ROOT' };
let room;
const rejected = (work, status) => assert.rejects(work, (error) => error.getStatus?.() === status);
async function main() {
  await db.tournament.create({ data: { id, name: 'Shared QR concurrency test', startDate: new Date(), endDate: new Date() } });
  room = await db.broadcastSession.create({ data: { title: 'Shared QR test', tournamentId: id, overlayTokenHash: randomUUID() } });
  await live.enable(room.id, 3, actor);
  await rejected(() => live.sharedCode(room.id, { id: randomUUID(), role: 'ADMIN' }), 403);
  const invite = await live.sharedCode(room.id, actor);
  const device = randomUUID();
  const duplicates = await Promise.all([live.redeem(invite.code, device), live.redeem(invite.code, device)]);
  assert.equal(duplicates[0].cameraId, duplicates[1].cameraId);
  assert.equal(duplicates[0].credential, duplicates[1].credential);
  const others = await Promise.all([live.redeem(invite.code, randomUUID()), live.redeem(invite.code, randomUUID())]);
  assert.equal(new Set([duplicates[0], ...others].map((c) => c.cameraId)).size, 3);
  await rejected(() => live.redeem(invite.code, randomUUID()), 409);
  const reopened = await Promise.all([live.sharedCode(room.id, actor), live.sharedCode(room.id, actor)]);
  assert.equal(reopened[0].code, invite.code);
  assert.equal(reopened[1].code, invite.code);
  assert.equal(reopened[0].expiresAt, invite.expiresAt);
  const rotated = await live.sharedCode(room.id, actor, true);
  await rejected(() => live.redeem(invite.code, randomUUID()), 401);
  for (const camera of [duplicates[0], ...others]) {
    assert.equal((await live.cameraConfig(camera.credential)).cameraId, camera.cameraId);
  }
  const recovered = await live.redeem(rotated.code, device);
  assert.equal(recovered.cameraId, duplicates[0].cameraId);
  assert.equal((await live.cameraConfig(recovered.credential)).cameraId, recovered.cameraId);
  await rejected(() => live.cameraConfig(duplicates[0].credential), 401);
  assert.equal((await live.redeem(rotated.code, device)).credential, recovered.credential);
  assert.equal(await db.broadcastCamera.count({ where: { broadcastId: room.id } }), 3);
  for (const camera of others) assert.equal((await live.cameraConfig(camera.credential)).cameraId, camera.cameraId);
  await db.broadcastJoinInvite.update({ where: { broadcastId: room.id }, data: { expiresAt: new Date(Date.now() - 1) } });
  await rejected(() => live.redeem(rotated.code, randomUUID()), 401);
  const closed = await live.sharedCode(room.id, actor);
  await live.revokeSharedCode(room.id, actor);
  await rejected(() => live.redeem(closed.code, randomUUID()), 401);
  const finalCode = await live.sharedCode(room.id, actor);
  await db.broadcastSession.update({ where: { id: room.id }, data: { status: 'ENDED' } });
  await rejected(() => live.redeem(finalCode.code, randomUUID()), 400);
  await db.broadcastSession.delete({ where: { id: room.id } });
  room = await db.broadcastSession.create({ data: { title: 'Single camera shared QR test', tournamentId: id, overlayTokenHash: randomUUID() } });
  const single = await live.enable(room.id, 1, actor);
  assert.equal(single.cameras.length, 1);
  const singleInvites = await Promise.all([live.sharedCode(room.id, actor), live.sharedCode(room.id, actor)]);
  assert.equal(singleInvites[0].code, singleInvites[1].code);
  const singleDevice = randomUUID();
  const joined = await live.redeem(singleInvites[0].code, singleDevice);
  assert.equal(joined.cameraId, single.cameras[0].id);
  assert.equal((await live.redeem(singleInvites[0].code, singleDevice)).credential, joined.credential);
  await rejected(() => live.redeem(singleInvites[0].code, randomUUID()), 409);
  await rejected(() => live.unpair(room.id, joined.cameraId, { id: randomUUID(), role: 'ADMIN' }), 403);
  await db.broadcastSession.update({ where: { id: room.id }, data: { status: 'LIVE', isPublic: true, activeCameraId: joined.cameraId, audioCameraId: joined.cameraId } });
  await rejected(() => live.unpair(room.id, joined.cameraId, actor), 409);
  await db.broadcastSession.update({ where: { id: room.id }, data: { status: 'INTERRUPTED', isPublic: false } });
  const released = await live.unpair(room.id, joined.cameraId, actor);
  assert.equal(released.activeCameraId, null);
  assert.equal(released.audioCameraId, null);
  await rejected(() => live.cameraConfig(joined.credential), 401);
  const replacement = await live.redeem(singleInvites[0].code, randomUUID());
  assert.equal(replacement.cameraId, joined.cameraId);
  await rejected(() => live.enable(room.id, 0, actor), 400);
  await rejected(() => live.enable(room.id, 7, actor), 400);
  console.log('PASS: single/multi shared QR, concurrent reopen stability, ROOT isolation, unique CAM allocation, recovery after QR reset, capacity, expiry, revocation, ended-room rejection, protected unpair and replacement via same QR');
}
main().catch((error) => { console.error(error.name, error.message); process.exitCode = 1; }).finally(async () => {
  if (room) await db.broadcastSession.deleteMany({ where: { id: room.id } });
  await db.tournament.deleteMany({ where: { id } });
  await db.$disconnect();
});
